-- Deploy arb-db:field_type to pg
-- requires: arbschema
-- requires: arbroles
-- requires: field_format

BEGIN;

CREATE TABLE IF NOT EXISTS standoff.field_type (
       field_type varchar(20) NOT NULL,
       field_format varchar(20) NOT NULL REFERENCES standoff.field_format DEFAULT 'literal',
       PRIMARY KEY (field_type));

GRANT SELECT ON TABLE standoff.field_type
TO standoffeditor, standoffuser;

GRANT INSERT, UPDATE, DELETE, SELECT ON TABLE standoff.field_type
TO standoffadmin;

INSERT INTO standoff.field_type VALUES
       ('abstract', 'literal'),
       ('addendum', 'literal'),
       ('afterword', 'person'),
       ('annotation', 'literal'),
       ('annotator', 'person'),
       ('author', 'person'),
       -- ('authortype', 'authortypes'),
       ('bookauthor', 'person'),
       ('bookpagination', 'pagination'),
       ('booksubtitle', 'literal'),
       ('booktitle', 'literal'),
       ('booktitleaddon', 'literal'),
       ('chapter', 'literal'),
       ('commentator', 'person'),
       ('date', 'date'),
       ('doi', 'literal'),
       ('edition', 'literal'),
       ('editor', 'person'),
       ('editora', 'person'),
       ('editoratype', 'editortype'),
       ('editorb', 'person'),
       ('editorbtype', 'editortype'),
       ('editorc', 'person'),
       ('editorctype', 'editortype'),
       ('editortype', 'editortype'),
       ('eid', 'literal'),
       ('entrysubtype', 'literal'),
       ('eprint', 'literal'),
       ('eprintclass', 'literal'),
       ('eprinttype', 'literal'),
       ('eventdate', 'date'),
       ('eventtitle', 'literal'),
       ('eventtitleaddon', 'literal'),
       -- ('file', 'literal'),
       ('foreword', 'person'),
       ('holder', 'person'),
       ('howpublished', 'literal'),
       ('indextitle', 'literal'),
       ('institution', 'literal'),
       ('introduction', 'person'),
       ('isan', 'literal'),
       ('isbn', 'literal'),
       ('ismn', 'literal'),
       ('isrn', 'literal'),
       ('issn', 'literal'),
       ('issue', 'literal'),
       ('issuesubtitle', 'literal'),
       ('iswc', 'literal'),
       ('journalsubtitle', 'literal'),
       ('journaltitle', 'literal'),
       ('journaltitleaddon', 'literal'),
       ('label', 'literal'),
       ('language', 'language'),
       ('library', 'literal'),
       ('location', 'literal'),
       ('mainsubtitle', 'literal'),
       ('maintitle', 'literal'),
       ('maintitleaddon', 'literal'),
       ('month', 'month'),
       ('nameaddon', 'literal'),
       ('note', 'literal'),
       ('number', 'integer'),
       ('organization', 'literal'),
       ('origauthor', 'person'),
       ('origdate', 'date'), -- Not in biblatex
       ('origlanguage', 'language'),
       ('origlocation', 'literal'),
       ('origpublisher', 'literal'),
       ('origtitle', 'literal'),
       -- ('origyear', 'year'),
       ('pages', 'range'),
       ('pagetotal', 'literal'),
       ('pagination', 'pagination'),
       ('part', 'literal'),
       ('publisher', 'literal'),
       ('pubstate', 'pubstate'),
       ('reprinttitle', 'literal'),
       ('series', 'literal'),
       -- ('shortauthor', 'literal'),
       -- ('shorteditor', 'literal'),
       -- ('shorthand', 'literal'),
       -- ('shorthandintro', 'literal'),
       -- ('shortjournal', 'literal'),
       -- ('shortseries', 'literal'),
       -- ('shorttitle', 'literal'),
       ('subtitle', 'literal'),
       ('title', 'literal'),
       ('titleaddon', 'literal'),
       ('translator', 'person'),
       ('type', 'type'),
       ('url', 'uri'),
       ('urldate', 'date'),
       ('venue', 'literal'),
       ('version', 'literal'),
       ('volume', 'literal'),
       ('volumes', 'literal'),
       ('year', 'literal'),
       -- SPECIAL FIELDS
       ('gender', 'gender')
       ON CONFLICT DO NOTHING;

COMMIT;
